apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "wordpress.name" . }}
    helm.sh/chart: {{ include "wordpress.chart" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "wordpress.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "wordpress.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag }}"
          ports:
            - name: http
              containerPort: 80
          env:
            - name: WORDPRESS_DB_NAME
              value: "{{ .Values.wordpress.db.name }}"
            - name: WORDPRESS_DB_USER
              value: "{{ .Values.wordpress.db.user }}"
            - name: WORDPRESS_DB_PASSWORD
              value: "{{ .Values.wordpress.db.password }}"