apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "wordpress.name" . }}
    helm.sh/chart: {{ include "wordpress.chart" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "wordpress.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80