services:
  app:
    build: ./roles/app/files/app_code
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    build: ./roles/db/db_code
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres_password